version: '2.0'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - .:/workspace:cached  

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database and redis container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - app-network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  app-network: