name: predict only

on:
  schedule:
    - cron: '0 0,1,2,3,4,5,7,8,10,11,12,13,14,16,17,19,20,21 * * *'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: python src/main.py --autobet=0
