name: predict and fetch results

on:
  schedule:
    - cron: '0 3-21/2 * * *'  # This runs the job every 2 hours between 3 & 21 at the 0th minute

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute main.py script # run main.py
        run: python src/main.py --autobet=0
